name: Build Docker y Push
inputs:
  username:
    description: docker repository owner
    required: true
    type: string
  password:
    description: docker repository token
    required: true
    type: string
  version:
    description: docker tag
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Login en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build - Push
      shell: bash
      run: |
        docker build -t ${{ inputs.username }}/gh_entregable:${{ inputs.version }} .
        docker push ${{ inputs.username }}/gh_entregable:${{ inputs.version }}
