name: Upload artifact
description: Subir imagen de docker al artifactory

outputs:
  artifact_id:
    description: 'Id del artifact'
    value: ${{ steps.version_name.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Save Docker image
      run: docker save --output image.tar "${autoria}"
      shell: bash

    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar
        retention-days: 10