name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Obtener version de la aplicación
        id: version
        run: python ./.github/actions/get-version.py

      - name: Construir aplicación de angular
        run: npm run build -- --prod

      - name: Construir imagen de Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nachocasado/gh_entregable:${{ steps.version.outputs.stdout }}

